# Generated by Django 5.2.3 on 2026-02-09 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percentage', models.IntegerField(default=5, help_text='Discount percentage (e.g. 5 = 5% off)')),
                ('max_usage', models.IntegerField(default=1, help_text='Maximum number of times this coupon can be used')),
                ('expired', models.BooleanField(default=False)),
                ('conference_year', models.IntegerField(help_text='Conference year this coupon is valid for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('order', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Issued'), (2, 'Paid')], default=1)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('conference_year', models.IntegerField()),
                ('related', models.CharField(blank=True, help_text='Groups multiple ticket types in one purchase', max_length=12)),
                ('multiple_tickets', models.BooleanField(default=False)),
                ('created_tickets', models.BooleanField(default=False, help_text='Whether attendee details (TicketSale) have been created')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_usages', to='tickets.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('diet', models.CharField(choices=[('Omnivorous', 'Omnivorous'), ('Vegetarian', 'Vegetarian'), ('Others', 'Others')], default='Omnivorous', max_length=30)),
                ('tagline', models.CharField(blank=True, max_length=100)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sales', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Student, Personal, Company, Patron', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this ticket includes')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Regular price', max_digits=10)),
                ('early_bird_price', models.DecimalField(decimal_places=2, default=0, help_text='Early bird price (0 = no early bird)', max_digits=10)),
                ('early_bird_count', models.IntegerField(default=0, help_text='Number of early bird tickets available')),
                ('regular_count', models.IntegerField(default=0, help_text='Number of regular tickets available')),
                ('conference_year', models.IntegerField(help_text='Conference year this ticket type belongs to')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which ticket types are displayed')),
            ],
            options={
                'ordering': ['display_order', 'price'],
                'unique_together': {('name', 'conference_year')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tickettype'),
        ),
    ]
