# Generated by Django 5.2.3 on 2025-08-02 22:51

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='conference_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description of the conference'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='conference_section_title',
            field=models.CharField(default='Conference Highlights', help_text='Title for the main conference section', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', 5)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'SVG code for the icon (optional)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('icon_svg', 0), ('title', 1), ('description', 2), ('link_text', 3), ('link_url', 4)]], {})}, help_text='Add feature cards to showcase conference highlights'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Hero section description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_text',
            field=models.CharField(default='Register Now', help_text='Primary call-to-action button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(default='Call for Papers', help_text='Secondary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle text (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='PyCon Nigeria', help_text='Main hero title', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='year_navigation_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Description for the year navigation section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='year_navigation_title',
            field=models.CharField(default='Browse Conference Years', help_text='Title for the year navigation section', max_length=200),
        ),
    ]
