# Generated by Django 5.2.3 on 2026-02-01 13:20

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_standardpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='conference_dates',
            field=models.CharField(blank=True, help_text='Conference dates (e.g., May 15-17, 2025)', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='conference_location',
            field=models.CharField(blank=True, help_text='Conference location (e.g., Lagos, Nigeria)', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© PyCon Nigeria. All rights reserved.', help_text='Footer copyright text', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_links',
            field=wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})}, help_text='Footer links (Privacy Policy, FAQs, etc.)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='login_button_text',
            field=models.CharField(blank=True, default='Login', help_text='Login button text (leave blank to hide)', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='login_button_url',
            field=models.URLField(blank=True, help_text='Login button URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='navigation_menu_items',
            field=wagtail.fields.StreamField([('menu_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'URL or page path (e.g., /tickets/ or https://example.com)', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_url', 1)]], {})}, help_text='Navigation menu items'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_description',
            field=models.CharField(blank=True, help_text='Newsletter description', max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_title',
            field=models.CharField(blank=True, default='Stay tuned!', help_text='Newsletter section title', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_section_title',
            field=models.CharField(blank=True, default='Sponsors', help_text='Sponsor section title', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsors',
            field=wagtail.fields.StreamField([('sponsor', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('patron', 'Patron'), ('startup', 'Startup'), ('media', 'Media Partner')]}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('tier', 2), ('website_url', 3)]], {})}, help_text='Add sponsors'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ticket_pricing',
            field=wagtail.fields.StreamField([('ticket', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., Student, Personal, Business', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., €60, $200, Free', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Buy Tickets', 'max_length': 50}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('tier_name', 0), ('price', 1), ('description', 2), ('button_text', 3), ('button_url', 4)]], {})}, help_text='Add ticket pricing tiers'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ticket_section_title',
            field=models.CharField(blank=True, default='Tickets', help_text='Ticket pricing section title', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='voting_button_text',
            field=models.CharField(blank=True, default='Vote Now', help_text='Voting button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='voting_button_url',
            field=models.URLField(blank=True, help_text='Voting button URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='voting_deadline',
            field=models.DateTimeField(blank=True, help_text='Voting deadline (for countdown timer)', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='voting_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Voting section description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='voting_section_title',
            field=models.CharField(blank=True, default='Community Voting', help_text='Voting section title', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL'),
        ),
    ]
