# Generated by Django 5.2.3 on 2026-02-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newslettersubscriber_homepage_conference_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='conference_year',
            field=models.IntegerField(blank=True, help_text='The conference year this page represents (e.g., 2024, 2025). Leave blank for current year.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme',
            field=models.CharField(choices=[('default', 'Default Theme (current design)'), ('theme_2024', '2024 Theme'), ('theme_2025', '2025 Theme'), ('theme_2026', '2026 Theme'), ('theme_legacy', 'Legacy Theme')], default='default', help_text='Select the design/theme for this conference year', max_length=50),
        ),
    ]
