# Generated by Django 5.2.3 on 2026-02-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_conference_year_homepage_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='ticket_pricing',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='ticket_section_title',
        ),
    ]
