# Generated by Django 5.2.3 on 2026-02-22 08:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_ticket_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='navigation_menu_items',
            field=wagtail.fields.StreamField([('menu_item', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'URL for direct link. Leave blank if this item has sub-menu items.', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'URL or page path', 'max_length': 200, 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('label', 2), ('link_url', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'blank': True, 'help_text': 'Add sub-menu items to show a dropdown. If empty, this will be a direct link.', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 0), ('link_url', 1), ('sub_items', 5)]], {})}, help_text='Navigation menu items'),
        ),
    ]
