# Generated by Django 5.2.3 on 2026-04-11 18:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_add_navigation_sub_items'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_headline', models.CharField(max_length=200)),
                ('hero_subheadline', models.CharField(blank=True, max_length=300)),
                ('hero_intro', wagtail.fields.RichTextField(blank=True)),
                ('hero_background_alt', models.CharField(blank=True, help_text='Alt text for the hero image (accessibility)', max_length=255)),
                ('hero_overlay_style', models.CharField(choices=[('dark', 'Dark overlay (recommended for photos)'), ('light', 'Light overlay'), ('none', 'No overlay')], default='dark', max_length=20)),
                ('hero_event_summary', wagtail.fields.RichTextField(blank=True, help_text='Dates, location, format, attendee scale (event overview)')),
                ('why_section_title', models.CharField(default='Why sponsor PyCon Nigeria?', max_length=200)),
                ('why_intro', wagtail.fields.RichTextField(blank=True)),
                ('why_benefits', wagtail.fields.StreamField([('benefit', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {})}, help_text='Key reasons to sponsor (e.g. talent, hiring, brand)')),
                ('audience_section_title', models.CharField(default='Audience profile', max_length=200)),
                ('audience_intro', wagtail.fields.RichTextField(blank=True)),
                ('audience_points', wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 400})}, help_text='Bullet-style audience segments')),
                ('packages_section_title', models.CharField(default='Sponsorship packages', max_length=200)),
                ('packages_intro', wagtail.fields.RichTextField(blank=True)),
                ('packages', wagtail.fields.StreamField([('package', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Short line, e.g. 'Best for: talent acquisition'", 'max_length': 300, 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Limited slots: 2'", 'max_length': 200, 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Visually emphasize this tier on the public page', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('tier_name', 0), ('price_label', 1), ('best_for', 2), ('benefits', 3), ('slots_note', 4), ('featured', 5)]], {})})),
                ('packages_supplement', wagtail.fields.RichTextField(blank=True, help_text='Add-ons, community impact, custom options, etc.')),
                ('cta_section_title', models.CharField(default='Partner with us', max_length=200)),
                ('cta_body', wagtail.fields.RichTextField(blank=True)),
                ('cta_button_label', models.CharField(blank=True, max_length=80)),
                ('cta_button_url', models.CharField(blank=True, help_text='Primary button URL or path (mailto: allowed)', max_length=500)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_url', models.CharField(blank=True, help_text='Secondary link, e.g. mailto:hello@example.org', max_length=500)),
                ('cta_urgency_line', models.CharField(blank=True, help_text='Short urgency line, e.g. limited slots / early commitment', max_length=300)),
                ('cta_trust_note', wagtail.fields.RichTextField(blank=True, help_text='Organizer credibility, nonprofit / community messaging')),
                ('hero_background', models.ForeignKey(blank=True, help_text='Optional full-width hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Sponsor Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
