# Generated by Django 5.2.3 on 2026-04-25 13:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sponsor_page'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='login_link_page',
            field=models.ForeignKey(blank=True, help_text='Optional. Internal page for sign-in; used before Login button URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='login_button_text',
            field=models.CharField(blank=True, default='Login', help_text='Sign-in control label (default: Sign In if left blank).', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='login_button_url',
            field=models.URLField(blank=True, help_text='Optional URL if no page is selected (e.g. external or SSO).'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navigation_menu_items',
            field=wagtail.fields.StreamField([('menu_item', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'For a direct link: pick an internal page, or leave blank and set URL below.', 'page_type': ['wagtailcore.Page'], 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'URL or path when the item is a direct link (not required if this item only opens a dropdown).', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 80, 'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Pick an internal page, or leave blank and set URL below.', 'page_type': ['wagtailcore.Page'], 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'External URL, /path, or #anchor (used when no page is selected).', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('page', 4), ('link_url', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'blank': True, 'help_text': 'Add sub-menu items to show a dropdown. If empty, this will be a direct link.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('link_url', 2), ('sub_items', 7)]], {})}, help_text='Navigation menu items'),
        ),
    ]
