# Generated by Django 5.2.3 on 2026-02-24 20:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('application_deadline', models.DateTimeField(help_text='Applications will close after this deadline')),
                ('max_grant_budget', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total budget cap for all grants', max_digits=12)),
                ('max_per_applicant', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maximum grant amount per applicant', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Grant Settings',
                'verbose_name_plural': 'Travel Grant Settings',
            },
        ),
        migrations.CreateModel(
            name='TravelGrantApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conference_year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('waitlisted', 'Waitlisted'), ('not_selected', 'Not Selected'), ('withdrawn', 'Withdrawn'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('passport_required', models.BooleanField(default=False)),
                ('first_time_pycon', models.BooleanField(default=False)),
                ('community_involvement', models.TextField(blank=True)),
                ('financial_need_reason', models.TextField()),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('other', 'Other')], max_length=30)),
                ('is_student', models.BooleanField(default=False)),
                ('estimated_transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estimated_accommodation_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('other_funding_sources', models.BooleanField(default=False)),
                ('other_funding_details', models.TextField(blank=True)),
                ('community_impact', models.TextField()),
                ('commit_to_share_learnings', models.BooleanField(default=False)),
                ('confirm_accurate', models.BooleanField(default=False)),
                ('agree_to_refund', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_grant_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'conference_year')},
            },
        ),
    ]
