# Generated by Django 5.2.3 on 2026-02-24 20:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chair', models.BooleanField(default=False, help_text='Chair can view all, make decisions, assign reviewers')),
                ('is_finance', models.BooleanField(default=False, help_text='Finance can view approved grants, mark payments')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant Reviewer Profile',
                'verbose_name_plural': 'Grant Reviewer Profiles',
            },
        ),
        migrations.CreateModel(
            name='GrantReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('has_conflict', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grants.travelgrantapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_assignments', to='grants.grantreviewerprofile')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('reviewer', 'application')},
            },
        ),
        migrations.CreateModel(
            name='TravelGrantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('reimbursement', 'Reimbursement'), ('direct', 'Direct payment')], default='reimbursement', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='grant_receipts/%Y/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='grants.travelgrantapplication')),
            ],
        ),
        migrations.CreateModel(
            name='TravelGrantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_score', models.IntegerField(help_text='Financial need (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact_score', models.IntegerField(help_text='Community impact (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('contribution_score', models.IntegerField(help_text='Contribution (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('diversity_score', models.IntegerField(help_text='Diversity/representation (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('weighted_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto-calculated average of dimension scores', max_digits=3)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='grants.grantreviewerassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
