# Generated by Django 5.2.3 on 2026-02-10 14:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CFPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_year', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('submission_deadline', models.DateTimeField(help_text='CFP will automatically close after this deadline')),
                ('allowed_durations', models.JSONField(blank=True, default=list, help_text='Allowed talk durations in minutes, e.g. [5, 20, 45, 90]')),
                ('guidelines', models.TextField(blank=True, help_text='CFP guidelines shown on the landing page (plain text or markdown)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CFP Settings',
                'verbose_name_plural': 'CFP Settings',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(help_text='Public abstract of the talk')),
                ('description', models.TextField(help_text='Detailed description for reviewers')),
                ('format', models.CharField(choices=[('talk', 'Talk'), ('workshop', 'Workshop'), ('tutorial', 'Tutorial'), ('lightning', 'Lightning Talk')], max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('audience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('prior_delivery', models.BooleanField(default=False, help_text='Has this talk been delivered before?')),
                ('prior_delivery_link', models.URLField(blank=True, help_text='Link to previous delivery (optional)')),
                ('slides_url', models.URLField(blank=True, help_text='Link to slides or repo (optional)')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('conference_year', models.IntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Use {speaker_name}, {proposal_title}, {conference_year} as placeholders')),
                ('template_type', models.CharField(choices=[('acceptance', 'Acceptance'), ('rejection', 'Rejection'), ('waitlist', 'Waitlist')], max_length=20)),
                ('conference_year', models.IntegerField()),
            ],
            options={
                'unique_together': {('template_type', 'conference_year')},
            },
        ),
        migrations.CreateModel(
            name='ProposalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('actor', models.CharField(help_text='Email or username of the person who performed the action', max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='cfp.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('snapshot_type', models.CharField(help_text="e.g. 'submission', 'edit'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cfp.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('has_conflict', models.BooleanField(default=False, help_text='Reviewer has declared a conflict of interest')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cfp.proposal')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score from 1 (weak) to 5 (strong)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(help_text='Internal review comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='cfp.reviewerassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chair', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviewer Profile',
                'verbose_name_plural': 'Reviewer Profiles',
            },
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cfp.reviewerprofile'),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('first_time_speaker', models.BooleanField(default=False)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('conference_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'conference_year')},
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='cfp.speaker'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('conference_year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('name', 'conference_year')},
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='cfp.track'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewerassignment',
            unique_together={('reviewer', 'proposal')},
        ),
    ]
