# Generated by Django 5.2.3 on 2026-02-10 14:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfpsettings',
            name='guidelines',
            field=wagtail.fields.RichTextField(blank=True, help_text='CFP guidelines shown on the landing page'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='abstract',
            field=wagtail.fields.RichTextField(help_text='Public abstract of the talk'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=wagtail.fields.RichTextField(help_text='Detailed description for reviewers'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=wagtail.fields.RichTextField(help_text='Speaker biography'),
        ),
    ]
